#!/bin/bash
# setup-ssl-permissions.sh
# ---------------------------------------------------------------------------
# Installs tight privilege-escalation wrappers for AdmixCentral's SSL manager
# and grants www-data passwordless sudo access ONLY to those wrappers.
#
# Security model
# ──────────────
# Granting sudo directly to /usr/bin/certbot is dangerous: certbot's
# --deploy-hook flag can execute arbitrary shell commands as root, giving an
# attacker with web-app RCE a trivial path to full root compromise.
# Similarly, `sudo nginx -c /evil.conf` allows loading a malicious config.
#
# Instead we install narrow wrapper scripts that:
#   • Accept only the exact arguments the app needs
#   • Hardcode every dangerous flag (method, paths, etc.)
#   • Validate all user-supplied inputs (domain, email, file path)
#   • Expose no hook flags, no config flags, no arbitrary subcommands
#
# The sudoers entry then names ONLY these wrappers — not certbot or nginx.
# ---------------------------------------------------------------------------
set -euo pipefail

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    echo "Run as root: sudo bash $0" >&2; exit 1
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
WRAPPERS_SRC="$SCRIPT_DIR/privileged"
WRAPPERS_DEST="/usr/local/bin"
SUDOERS_FILE="/etc/sudoers.d/admixcentral"
APP_USER="www-data"

WRAPPER_NAMES=(
    admixcentral-request-cert
    admixcentral-cert-delete
    admixcentral-nginx-config-write
    admixcentral-nginx-test
    admixcentral-nginx-reload
)

echo "==> Installing privilege wrapper scripts..."
for name in "${WRAPPER_NAMES[@]}"; do
    src="$WRAPPERS_SRC/$name"
    dest="$WRAPPERS_DEST/$name"
    if [[ ! -f "$src" ]]; then
        echo "ERROR: Missing wrapper: $src" >&2; exit 1
    fi
    install -o root -g root -m 0755 "$src" "$dest"
    echo "    Installed: $dest"
done

echo ""
echo "==> Writing sudoers rule (wrappers only — NOT certbot/nginx directly)..."

{
    echo "# AdmixCentral SSL management — generated by setup-ssl-permissions.sh"
    echo "# www-data may ONLY run these specific wrapper scripts, not certbot or nginx directly."
    echo "# This prevents --deploy-hook injection and arbitrary nginx config loading."
    for name in "${WRAPPER_NAMES[@]}"; do
        echo "$APP_USER ALL=(ALL) NOPASSWD: $WRAPPERS_DEST/$name"
    done
} > "$SUDOERS_FILE"

chmod 0440 "$SUDOERS_FILE"

if ! visudo -cf "$SUDOERS_FILE" > /dev/null 2>&1; then
    echo "ERROR: sudoers syntax invalid — removing file." >&2
    rm -f "$SUDOERS_FILE"
    exit 1
fi

echo ""
echo "✅ Done. Summary:"
echo "   Wrappers installed in: $WRAPPERS_DEST"
echo "   Sudoers file:          $SUDOERS_FILE"
echo ""
echo "   www-data may now run:"
for name in "${WRAPPER_NAMES[@]}"; do
    echo "     sudo $WRAPPERS_DEST/$name"
done
echo ""
echo "   www-data may NOT run certbot, nginx, or systemctl directly."
